using MooreHotels.Domain.Enums;
using MooreHotels.Application.DTOs.Pricing;

namespace MooreHotels.Application.DTOs;

public record BookingDto(
    Guid Id,
    string BookingCode,
    Guid? RoomId,
    string GuestId,
    string GuestFirstName,
    string GuestLastName,
    string GuestEmail,
    string GuestPhone,
    DateTime CheckIn,
    DateTime CheckOut,
    BookingStatus Status,
    decimal Amount,
    PaymentStatus PaymentStatus,
    PaymentMethod? PaymentMethod,
    string? TransactionReference,
    string? Notes,
    DateTime CreatedAt,
    string? PaymentUrl = null,
    string? PaymentInstruction = null,
    string? NotificationMessage = null,
    string? RefundReference = null,
    DateTime? PaymentExpiresAtUtc = null,
    string? GuestAccessToken = null,
    decimal? RefundAmount = null,
    string? RefundChannel = null,
    string? RefundEvidenceType = null,
    Guid? RefundApprovedByUserId = null,
    DateTime? RefundApprovedAtUtc = null,
    Guid? RefundProcessedByUserId = null,
    DateTime? RefundProcessedAtUtc = null,
    DateTime? GuestAccessExpiresAtUtc = null,
    int AdultCount = 1,
    int ChildCount = 0,
    string? PrivacyPolicyVersion = null,
    string? BookingTermsVersion = null,
    DateTime? PoliciesAcceptedAtUtc = null,
    Guid? QuoteId = null,
    string Currency = "NGN",
    decimal RoomSubtotal = 0,
    decimal DiscountAmount = 0,
    decimal IncludedTaxAmount = 0,
    decimal TaxAmount = 0,
    decimal FeeAmount = 0,
    IReadOnlyList<PricingQuoteLineDto>? PriceBreakdown = null,
    Guid? RoomTypeId = null,
    string? RoomTypeCode = null,
    string? RoomTypeName = null,
    int RoomQuantity = 1,
    IReadOnlyList<ReservationRoomDto>? Rooms = null,
    FolioSummaryDto? Folio = null,
    decimal? RefundApprovedAmount = null,
    ReservationPolicySnapshotDto? ReservationPolicy = null);
