using MooreHotels.Domain.Enums;

namespace MooreHotels.Application.DTOs;

public record BookingDto(
    Guid Id,
    string BookingCode,
    Guid RoomId,
    string GuestId,
    string GuestFirstName,
    string GuestLastName,
    string GuestEmail,
    string GuestPhone,
    DateTime CheckIn,
    DateTime CheckOut,
    BookingStatus Status,
    decimal Amount,
    PaymentStatus PaymentStatus,
    PaymentMethod? PaymentMethod,
    string? TransactionReference,
    string? Notes,
    DateTime CreatedAt,
    string? PaymentUrl = null,
    string? PaymentInstruction = null,
    string? NotificationMessage = null,
    string? RefundReference = null,
    DateTime? PaymentExpiresAtUtc = null,
    string? GuestAccessToken = null,
    decimal? RefundAmount = null,
    string? RefundChannel = null,
    string? RefundEvidenceType = null,
    Guid? RefundApprovedByUserId = null,
    DateTime? RefundApprovedAtUtc = null,
    Guid? RefundProcessedByUserId = null,
    DateTime? RefundProcessedAtUtc = null,
    DateTime? GuestAccessExpiresAtUtc = null,
    int AdultCount = 1,
    int ChildCount = 0,
    string? PrivacyPolicyVersion = null,
    string? BookingTermsVersion = null,
    DateTime? PoliciesAcceptedAtUtc = null);
