using MooreHotels.Domain.Enums;
using MooreHotels.Application.DTOs.Pricing;

namespace MooreHotels.Application.DTOs;

public sealed record PublicBookingDto(
    Guid Id,
    string BookingCode,
    Guid? RoomId,
    string GuestFirstName,
    string GuestLastName,
    string GuestEmail,
    DateTime CheckIn,
    DateTime CheckOut,
    BookingStatus Status,
    decimal Amount,
    PaymentStatus PaymentStatus,
    PaymentMethod? PaymentMethod,
    DateTime CreatedAt,
    string? PaymentUrl = null,
    string? PaymentInstruction = null,
    string? NotificationMessage = null,
    DateTime? PaymentExpiresAtUtc = null,
    string? GuestAccessToken = null,
    DateTime? GuestAccessExpiresAtUtc = null,
    int AdultCount = 1,
    int ChildCount = 0,
    Guid? QuoteId = null,
    string Currency = "NGN",
    decimal RoomSubtotal = 0,
    decimal DiscountAmount = 0,
    decimal IncludedTaxAmount = 0,
    decimal TaxAmount = 0,
    decimal FeeAmount = 0,
    IReadOnlyList<PricingQuoteLineDto>? PriceBreakdown = null,
    Guid? RoomTypeId = null,
    string? RoomTypeCode = null,
    string? RoomTypeName = null,
    int RoomQuantity = 1,
    IReadOnlyList<ReservationRoomDto>? Rooms = null,
    FolioSummaryDto? Folio = null,
    ReservationPolicySnapshotDto? ReservationPolicy = null);
